### ISSUE TITLE
Can't get access token from local storage

### ISSUE THREAD

**Issue by 8hrsk** [enginestein/cai.js#1]
Maybe I'm not understanding smth but there's no such key for me. Tried several browsers, but got the same result
![image](https://github.com/enginestein/cai.js/assets/125183117/4ce90838-6e38-4e27-871a-1e1bdce81daa)

Did they change auth methods? Access token is now storaged somewhere else? Does this library work now?

**Comment by enginestein** [comment]
hmm, well apparently character.ai has updated the UI. try going to beta.character.ai and redo it, I am quite busy these days; Whenever I'm free, I'll update the framework for the new UI.

**Comment by enginestein** [comment]
Okay. I found out. Go to Application tab, then Local Storage, then beta.character.ai, then copy the 'value' in 'char_token'.
